### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by clbanning** [dominikh/go-simple#9]
I have: 

```
func (p *FS) FindID(id string) bool {
  ...
 fi, err := os.Stat(path.Join(p.path, id))
   if err != nil {
      return false
   }
   m := fi.Mode()
   if (m & os.ModeType) > 0 {
      return false
   }
   return true
}
```

and am getting:

... "should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>".

But "m & os.ModeType" is a unit32 value not a bool value.

**Comment by dominikh** [comment]
`return (m & os.ModeType) == 0`

**Comment by dominikh** [comment]
To expand: the expression is `(m & os.ModeType) > 0`, not `m & os.ModeType`. Because the positive branch returns false, to turn it into a plain return statement, it would be `return !((m & os.ModeType) > 0)` and that simplifies to `return (m & os.ModeType) == 0` (in this instance, because the value cannot be less than 0).
